name: action context

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'context'
        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "commit id => $COMMIT_ID"
