name: load secret

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret
        env:
          PASS: ${{ secrets.TESTSECRET }}
        run: echo my password is $PASS
